// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkvheuhwqrdkyjnupoai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrdmhldWh3cXJka3lqbnVwb2FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NjIwOTQsImV4cCI6MjA3NDEzODA5NH0.0JFUzcNcSI5ywHswK7evayXo5E7Na-fl2llqjZHGWCY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});